version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
    assignees:
      - Stanzilla
    labels:
      - dependencies

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
    assignees:
      - Stanzilla
    labels:
      - dependencies
